import type { Metadata } from "next";
import {Poppins, Unbounded } from "next/font/google";
import Footer from "./components/Footer";
import "./globals.css";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
});

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700","800","900"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${unbounded.variable} antialiased`}
      >
        {children}
      </body>
      <Footer />
    </html>
  );
}
