import type { Metadata } from "next";
import {Poppins, Unbounded } from "next/font/google";
import Footer from "./components/Footer";
import "./globals.css";
import Script from "next/script";
import CookieButton from "./components/CookieButton";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
});

const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700","800","900"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      {/* Load Termly client-side only */}
      <Script
        id="termly-banner"
        src="https://app.termly.io/embed.min.js"
        strategy="afterInteractive"
        data-auto-block="on"
        data-website-uuid="7ab46f4c-621c-4de7-b860-bc69e2a9d53b"
      />
      </head>
      <body
        className={`${poppins.variable} ${unbounded.variable} antialiased`}
      >
        {children}
      </body>
      <Footer />
      <CookieButton />
    </html>
  );
}
